# Jekyll configuration

name: Eric
description: Welcome to my world！


# url is currently only used only for the RSS feed in feed.xml
url: https://SweetEric.github.io/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "cn" 

# theme: minima
# theme
# theme: phantom_jekyll_theme

paginate: 10
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

    
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]    
